config/routes.rb
Rails.application.routes.draw do
root :to => 'mountains#index'
get '/mountains' => 'mountains#index'
get '/mountains/new' => 'mountains#new', :as => :new_mountain
post '/mountains' => 'mountains#create'
get '/mountains/:id' => 'mountains#show', :as => :mountain
get '/mountains/:id/edit' => 'mountains#edit', :as => :edit_mountain
post '/mountains/:id' => 'mountains#update'
delete '/mountains/:id' => 'mountains#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token # You only need this for hand written forms (don't do that).
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
    @mountains = Mountain.all
    @mountain = Mountain.new
  end

  def show
    @mountain = Mountain.find params[:id]
  end

  def new
  @mountain = Mountain
  end

  def create
  mountain = Mountain.new
  mountain.name = params[:name]
  mountain.image = params[:image]
  mountain.height = params[:height]
  mountain.ascent = params[:ascent]
  mountain.country = params[:country]
  mountain.save
  redirect_to mountain_path(mountain.id)
  end

  def edit
  @mountain = Mountain.find params[:id]
  end

  def update
    mountain = Mountain.find params[:id]
    mountain.name = params[:name]
    mountain.image = params[:image]
    mountain.height = params[:height]
    mountain.ascent = params[:ascent]
    mountain.country = params[:country]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def destroy
  mountain = Mountain.find params[:id]
  mountain.destroy
  redirect_to mountains_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mountain Peak!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="fixed">
    <h1><%= @mountain.name if @mountain.name.present? %> PEAK!</h1>
    <nav>
      <%= link_to 'Mountain Tops', mountains_path %>
    |
      <%= link_to 'New Mountain', new_mountain_path %>
    </nav>
    </div>

    <div class="container">
    <%= yield %>
    </div>

  </body>
</html>

app/views/mountains/edit.html.erb
<h2>EDIT MOUNTAIN!</h2>
<div class="form">
<p><i><strong>You Had One Job!</strong></i></p>

<form action="<%= mountain_path(@mountain.id) %>" method="post">
  <label>
    Name:
    <input type="text" name="name" required autofocus value="<%= @mountain.name %>">
  </label>

  <label>
    Image:
    <input type="text" name="image" value="<%= @mountain.image %>">
  </label>

  <label>
    Height (metres):
    <input type="number" name="height" value="<%= @mountain.height %>">
  </label>

  <label>
    First Ascent (year):
    <input type="number" name="ascent" value="<%= @mountain.ascent %>">
  </label>

  <label>
    Country:
    <input type="text" name="country" value="<%= @mountain.country %>">
  </label>

  <button><strong>UPDATE!</strong></button>
</form>
</div>

app/views/mountains/index.html.erb
<h2>MOUNTAIN TOPS!</h2>
<div class="form">
<p><i><strong>Check out them mountains!</strong></i></p>

<% @mountains.each do |mountain| %>
  <p class="links">
    <%= link_to mountain.name, mountain_path(mountain.id) %>
  </p>
<% end %>
</div>

app/views/mountains/new.html.erb
<h2>NEW MOUNTAIN!</h2>
<div class="form">
<p><i><strong>Sick! A New Mountain!</strong></i></p>

<form action="<%= mountains_path %>" method="post">
  <label>
    Name:
    <input type="text" placeholder="Mount Everest" name="name" required autofocus>
  </label>

  <label>
    Image:
    <input type="text" placeholder="https://www.img..." name="image">
  </label>

  <label>
    Height (metres):
    <input type="number" placeholder="8848" name="height">
  </label>

  <label>
    First Ascent (year):
    <input type="number" placeholder="1953" name="ascent" max="4">
  </label>

  <label>
    Country:
    <input type="text" placeholder="Nepal/China" name="country">
  </label>

  <button><strong>UPLOAD!</strong></button>
</form>
</div>

app/views/mountains/show.html.erb
<div class="showimage">
  <%= image_tag @mountain.image, :class => 'bg' if @mountain.image.present? %>
</div>

<div class="show">
<ul>
  <li>Height: <%= number_with_delimiter(@mountain.height) %> metres </li>
  <li>First Ascent: <%= @mountain.ascent %> </li>
  <li>Country: <%= @mountain.country %> </li>
</ul>

<div class="controls">
  <%= link_to 'Edit mountain', edit_mountain_path(@mountain.id), :class => 'editlink' %>
  -
  <%= button_to 'Delete mountain', mountain_path(@mountain.id), :method => 'delete', :class => 'deletebutton' %>
</div>
</div>